#!/bin/bash
# build prometheus if doesn't exist

if [ -f ${GOBIN}/prometheus ]; then
  mkdir -p $GOPATH/src/github.com/prometheus
  cd $GOPATH/src/github.com/prometheus
  git clone https://github.com/prometheus/prometheus.git
  cd prometheus
  make build
fi
